{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Release.Name }}-gateway
spec:
  gatewayClassName: {{ .Values.gateway.className }}
  listeners:
  - name: http
    protocol: HTTP
    port: {{ .Values.gateway.port }}
    hostname: {{ .Values.gateway.host }}
{{- end }}

