{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}-route
spec:
  parentRefs:
  - name: {{ .Release.Name }}-gateway
  hostnames:
  - {{ .Values.gateway.host }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: bankapp-service
      port: {{ .Values.bankapp.service.port }}
{{- end }}

